version: "3.2"
services:
        jscout:
                build: jscout/
                restart: always
                depends_on:
                        - "goscout"
                volumes:
                        - type: volume
                          source: jscout_caddydir
                          target: /.caddy
                          volume:
                                 nocopy: true
                environment:
                        JSCOUT_DOMAIN:
                        GOSCOUT_HOST: "goscout"
                ports:
                        - "80:80"
                        - "443:443"
        goscout:
                build: goscout/
                restart: always
                depends_on:
                        - "strangedb"
                environment:
                        GOSCOUT_SQL_USER: "strangescout"
                        GOSCOUT_SQL_PASSWD: "${STRANGESCOUT_SQL_PASSWD}"
                        GOSCOUT_SQL_HOST: "strangedb"
                expose:
                        - "15338"
                ports:
                        - "15338:15338"
        
        strangedb:
                image: mariadb
                restart: always
                volumes:
                        - type: volume
                          source: strangedb
                          target: /var/lib/mysql
                environment:
                        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
                        MYSQL_DATABASE: "strangescout"
                        MYSQL_PASSWORD: "${STRANGESCOUT_SQL_PASSWD}"
                        MYSQL_USER: "strangescout" 
                expose:
                        - "3306"
                ports:
                        - "3306:3306"

volumes:
        strangedb:
        jscout_caddydir:
