version: "3.5"
services:
        jscout:
                build: jscout/
                restart: always
                depends_on:
                        - "goscout"
                volumes:
                        - type: volume
                          source: jscout_caddydir
                          target: /.caddy
                          volume:
                                 nocopy: true
                environment:
                        JSCOUT_DOMAIN: ${JSCOUT_DOMAIN?did not set the domain name}
                        JSCOUT_LETS_ENCRYPT_EMAIL: ${JSCOUT_LETS_ENCRYPT_EMAIL?did not set the Lets Encrylt email}
                        GOSCOUT_HOST: "goscout"
                ports:
                        - "80:80"
                        - "443:443"
        goscout:
                build: goscout/
                restart: always
                depends_on:
                        - "strangedb"
                environment:
                        GOSCOUT_SQL_USER: "strangescout"
                        GOSCOUT_SQL_PASSWD: "${STRANGESCOUT_SQL_PASSWD?did not set password}"
                        GOSCOUT_SQL_HOST: "strangedb"
                        GOSCOUT_EVENT_HARDCODE:
                expose:
                        - "15338"
        strangedb:
                image: mariadb
                restart: always
                volumes:
                        - type: volume
                          source: strangedb
                          target: /var/lib/mysql
                environment:
                        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
                        MYSQL_DATABASE: "strangescout"
                        MYSQL_PASSWORD: "${STRANGESCOUT_SQL_PASSWD?did not set password!}"
                        MYSQL_USER: "strangescout" 
                expose:
                        - "3306"
                ports:
                        - "{$MYSQL_PUBLIC_PORT:-3306}:3306"

volumes:
        strangedb:
                name: {$PREFIX-prod}_strangedb
        jscout_caddydir: # stores certs--if you don't persist these you will QUICKLY hit a Let's Encrypt ratelimit!
                name: ${PREFIX-prod}_jscout_caddydir
